version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - POSTGRES_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/connectattoo?schema=public&connect_timeout=60
    environment:
      - NODE_ENV=development
      - POSTGRES_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/connectattoo?schema=public&connect_timeout=60
    restart: 'on-failure'
    env_file:
      - .env
    ports:
      - ${PORT:-3000}:${PORT:-3000}
      - 5555:5555
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      - connectattoo
    volumes:
      - .:/api
      - /api/node_modules
    command:
      - /bin/sh
      - -c
      - |
        git submodule update --remote
        npx prisma migrate dev
        npm run start:dev

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - connectattoo
    volumes:
      - ./scripts/docker/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d connectattoo -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  cloudbeaver:
    container_name: dbeaver
    image: dbeaver/cloudbeaver
    restart: unless-stopped
    ports:
       - 8978:8978
    networks:
      - connectattoo
    volumes:
      - connectattoo:/opt/cloudbeaver/workspace

volumes:
  connectattoo:
    name: connectattoo

networks:
  connectattoo:
    name: connectattoo
    driver: bridge
