version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - POSTGRES_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/connectattoo?schema=public&connect_timeout=60
    environment:
      - NODE_ENV=development
      - POSTGRES_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/connectattoo?schema=public&connect_timeout=60
    restart: 'on-failure'
    env_file:
      - .env
    ports:
      - ${PORT:-3000}:${PORT:-3000}
      - 5555:5555
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      - connectattoo
    volumes:
      - .:/api
    entrypoint: scripts/docker/entrypoint.sh

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - connectattoo
    volumes:
      - ./.docker/postgres/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d connectattoo -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8082:8080
    networks:
      - connectattoo
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_SYSTEM=pgsql
      - ADMINER_DESIGN=hydra

volumes:
  connectattoo:
    name: connectattoo

networks:
  connectattoo:
    name: connectattoo
    driver: bridge
