version: '3.8'

services:
  app:
    container_name: app
    build: .
    environment:
      - NODE_ENV=development
    restart: 'on-failure'
    volumes:
      - ./data/app:/root/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - mongo
    links:
      - postgres
      - mongo
    networks:
      - connectattoo

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - connectattoo

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=connectattoo
    env_file:
      - .env
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongo:/data/mongo
    networks:
      - connectattoo

volumes:
  postgres:
  mongo:


networks:
  connectattoo:
    driver: bridge
